// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCJ_soosSoSHAtMes2nHGkVpVS9y4Jhqw',
    appId: '1:42239832712:web:3fbcfc80d412e4671ce53d',
    messagingSenderId: '42239832712',
    projectId: 'visit-mongolia',
    authDomain: 'visit-mongolia.firebaseapp.com',
    storageBucket: 'visit-mongolia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD30T67gPNWvSbmWYd0-UmIyoknjUNL7Zc',
    appId: '1:42239832712:android:035707127e2ff46a1ce53d',
    messagingSenderId: '42239832712',
    projectId: 'visit-mongolia',
    storageBucket: 'visit-mongolia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOn_Jh2ea7MF6isjig1Cgx14sx2TVS6G4',
    appId: '1:42239832712:ios:32ade4fab1079bbc1ce53d',
    messagingSenderId: '42239832712',
    projectId: 'visit-mongolia',
    storageBucket: 'visit-mongolia.appspot.com',
    iosBundleId: 'com.example.visitMongolia',
  );
}
